package com.amal.jarvis;
import android.content.*;import android.media.*;import android.os.*;import android.util.Base64;import ai.picovoice.eagle.*;
public class VoiceProfile {
 public interface Progress{void update(String s);}
 public static volatile boolean cancel=false;
 static AudioRecord recorder(int rate,int count){int size=Math.max(count*2,AudioRecord.getMinBufferSize(rate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT));return new AudioRecord(MediaRecorder.AudioSource.VOICE_RECOGNITION,rate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,size);}
 static short[] read(AudioRecord r,int n)throws Exception{short[] b=new short[n];int pos=0;while(pos<n&&!cancel){int k=r.read(b,pos,n-pos);if(k<=0)throw new Exception("Microphone unavailable");pos+=k;}if(cancel)throw new Exception("Cancelled");return b;}
 static void enroll(Context c,Progress cb)throws Exception{cancel=false;EagleProfiler p=new EagleProfiler.Builder().setAccessKey(Vault.get(c,"pico")).build(c);AudioRecord r=null;try{int n=p.getFrameLength();r=recorder(p.getSampleRate(),n);r.startRecording();long end=SystemClock.elapsedRealtime()+90000;float done=0;while(done<100&&SystemClock.elapsedRealtime()<end&&!cancel&&Session.valid(c)){done=p.enroll(read(r,n));cb.update("Read naturally in a quiet room. Enrollment: "+(int)done+"%");}if(done<100||!Session.valid(c)||cancel)throw new Exception("Enrollment incomplete. Please try again.");EagleProfile profile=p.export();try{Vault.put(c,"profile",Base64.encodeToString(profile.getBytes(),2));}finally{profile.delete();}cb.update("Voice enrolled. Owner voice check is enabled.");}finally{if(r!=null){try{r.stop();}catch(Exception e){}r.release();}p.delete();}}
 static boolean verify(Context c)throws Exception{cancel=false;String saved=Vault.get(c,"profile");if(saved.isEmpty())return false;Eagle e=new Eagle.Builder().setAccessKey(Vault.get(c,"pico")).build(c);EagleProfile p=new EagleProfile(Base64.decode(saved,2));AudioRecord r=null;try{int n=Math.max(e.getMinProcessSamples(),e.getSampleRate()*3);r=recorder(e.getSampleRate(),n);r.startRecording();float[] scores=e.process(read(r,n),new EagleProfile[]{p});return Session.valid(c)&&!cancel&&scores!=null&&scores[0]>=.75f;}finally{if(r!=null){try{r.stop();}catch(Exception x){}r.release();}p.delete();e.delete();}}
}
